name: 'Push to BalenaCloud'
branding:
  color: "yellow"
  icon: "box"
description: 'Push your code to BalenaCloud using balena-cli'
inputs:
  api-token:
    description: 'BalenaCloud API Key'
    required: true
  application-name:
    description: "The name of the BalenaCloud Application that you'll be pushing to"
    required: true
  application-path:
    description: "Optional. Provide a subfolder path to your BalenaCloud application, example: ./balena-wpe"
    default: "."
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    API_TOKEN: ${{ inputs.api-token }}
    APPLICATION_NAME: ${{ inputs.application-name }}
    APPLICATION_PATH: ${{ inputs.application-path }}
